import { hsva } from '../util';
export class Cube {
    private _pos: number[] = [];
    private _col: number[] = [];
    private _idx: number[] = [];
    private _norm: number[] = [];

    get pos(): number[] {
        return this._pos;
    }
    get col(): number[] {
        return this._col;
    }
    get normal(): number[] {
        return this._norm;
    }
    get idx(): number[] {
        return this._idx;
    }
    constructor(size: number) {
        this.init(size);
    }
    init(size: number): void {
        const hs = size * 0.5;
        this._pos = [
            -hs,
            -hs,
            hs,
            hs,
            -hs,
            hs,
            hs,
            hs,
            hs,
            -hs,
            hs,
            hs,
            -hs,
            -hs,
            -hs,
            -hs,
            hs,
            -hs,
            hs,
            hs,
            -hs,
            hs,
            -hs,
            -hs,
            -hs,
            hs,
            -hs,
            -hs,
            hs,
            hs,
            hs,
            hs,
            hs,
            hs,
            hs,
            -hs,
            -hs,
            -hs,
            -hs,
            hs,
            -hs,
            -hs,
            hs,
            -hs,
            hs,
            -hs,
            -hs,
            hs,
            hs,
            -hs,
            -hs,
            hs,
            hs,
            -hs,
            hs,
            hs,
            hs,
            hs,
            -hs,
            hs,
            -hs,
            -hs,
            -hs,
            -hs,
            -hs,
            hs,
            -hs,
            hs,
            hs,
            -hs,
            hs,
            -hs,
        ];
        this._norm = [
            -1.0,
            -1.0,
            1.0,
            1.0,
            -1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            -1.0,
            1.0,
            1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            1.0,
            -1.0,
            1.0,
            1.0,
            -1.0,
            1.0,
            -1.0,
            -1.0,
            -1.0,
            1.0,
            -1.0,
            -1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            1.0,
            -1.0,
            -1.0,
            1.0,
            -1.0,
            1.0,
            -1.0,
            -1.0,
            1.0,
            1.0,
            -1.0,
            -1.0,
            1.0,
            1.0,
            -1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            -1.0,
            1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            1.0,
            -1.0,
            1.0,
            1.0,
            -1.0,
            1.0,
            -1.0,
        ];
        const col = [];
        for (let i = 0; i < this._pos.length / 3; i++) {
            const tc = hsva((360 / this._pos.length / 3) * i, 1, 1, 1);
            if (!tc) return;
            col.push(tc[0], tc[1], tc[2], tc[3]);
        }
        this._col = col;
        const st = [
            0.0,
            0.0,
            1.0,
            0.0,
            1.0,
            1.0,
            0.0,
            1.0,
            0.0,
            0.0,
            1.0,
            0.0,
            1.0,
            1.0,
            0.0,
            1.0,
            0.0,
            0.0,
            1.0,
            0.0,
            1.0,
            1.0,
            0.0,
            1.0,
            0.0,
            0.0,
            1.0,
            0.0,
            1.0,
            1.0,
            0.0,
            1.0,
            0.0,
            0.0,
            1.0,
            0.0,
            1.0,
            1.0,
            0.0,
            1.0,
            0.0,
            0.0,
            1.0,
            0.0,
            1.0,
            1.0,
            0.0,
            1.0,
        ];
        this._idx = [
            0,
            1,
            2,
            0,
            2,
            3,
            4,
            5,
            6,
            4,
            6,
            7,
            8,
            9,
            10,
            8,
            10,
            11,
            12,
            13,
            14,
            12,
            14,
            15,
            16,
            17,
            18,
            16,
            18,
            19,
            20,
            21,
            22,
            20,
            22,
            23,
        ];
    }
}
